## Australian Grocery Store Data Analysis
- Name: Vivaan Bhandari
- Division: B
- Roll No: 44

In [54]:
# Setup
import pandas as pd

In [55]:
#
sales_2017_df = pd.read_csv("Australian_Grocery_Store_Data_2017.csv")
sales_2017_df.sort_values("receipt_id").head(3)

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin
95656,0001c063-2d32-4380-9db6-de20c5b48f59,1/16/2017 1:54:07 AM,1163,Brushed Potatoes 5kg bag,1.000,cash,4.5,4.99,0.49
14443,0001c063-2d32-4380-9db6-de20c5b48f59,1/16/2017 1:54:07 AM,2010,Banana Cavendish,1.364,cash,2.0,1.99,-0.01
91984,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,1008,Broccoli,0.626,cash,0.0,3.50,3.50

In [56]:
#
sales_2018_df = pd.read_csv("Australian_Grocery_Store_Data_2018.csv")
sales_2018_df.sort_values("receipt_id").head(3)

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin
18180,0002d6fc-1efa-43de-ba27-a683a1ee7ab8,5/20/2018 5:28:28 PM,2032,Orange navel,1.426,cash,0.0,2.99,2.99
9272,0002d6fc-1efa-43de-ba27-a683a1ee7ab8,5/20/2018 5:28:28 PM,2010,Banana Cavendish,1.436,cash,2.0,1.99,-0.01
22346,0002d6fc-1efa-43de-ba27-a683a1ee7ab8,5/20/2018 5:28:28 PM,9332769000139,Eggs 700g,1.000,cash,2.7,3.20,0.50

In [57]:
# Concatenating the data of 2017 and 2018 to make one sales dataframe that has data for both 2017 and 2018.
sales_df = pd.concat([sales_2017_df, sales_2018_df])
sales_df.sort_values("receipt_id")

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin
14443,0001c063-2d32-4380-9db6-de20c5b48f59,1/16/2017 1:54:07 AM,2010,Banana Cavendish,1.364,cash,2.0,1.99,-0.01
95656,0001c063-2d32-4380-9db6-de20c5b48f59,1/16/2017 1:54:07 AM,1163,Brushed Potatoes 5kg bag,1.000,cash,4.5,4.99,0.49
1171,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,2002,Apples Granny Smith,0.352,cash,0.0,3.00,3.00
88419,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,2124,mango 2for 3.00,1.000,cash,0.0,3.00,3.00
94804,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,1073,Potato Desiree,1.370,cash,0.0,2.99,2.99
...,...,...,...,...,...,...,...,...,...
120204,fffe8a4a-313d-4817-a94f-680cc27111fe,3/28/2018 3:51:37 PM,1167,Sweet potatoes Purple,1.134,magcard,2.5,2.99,0.49
15239,fffee230-046f-4ad5-92e3-ef935ddc926d,2/23/2017 1:42:00 AM,9320800000040,Berries Strawberry (medium),1.000,cash,0.0,2.50,2.50
41417,ffff062a-d847-4c6f-821e-8453fbaa8b90,1/31/2018 12:00:09 PM,1037,Garlic loose,0.176,cash,0.0,10.00,10.00
22079,ffff062a-d847-4c6f-821e-8453fbaa8b90,1/31/2018 12:00:09 PM,9332769000139,Eggs 700g,1.000,cash,2.7,3.20,0.50
40078,ffff062a-d847-4c6f-821e-8453fbaa8b90,1/31/2018 12:00:09 PM,1232,onion brown 2kg large,1.000,cash,3.5,4.50,1.00

In [58]:
#
item_categories_df = pd.read_csv("Australian_Grocery_Store_Data_Only_Items_Categories.csv")
item_categories_df

                        item_name   main_category sub_category
0            2kg Royal gala apple   Fresh Produce       Apples
1      Apple Granny Smith 1kg bag   Fresh Produce       Apples
2     Apple Granny smith 2kg Bags   Fresh Produce       Apples
3                      apple Jazz   Fresh Produce       Apples
4                  Apple Jonathan   Fresh Produce       Apples
...                           ...             ...          ...
1261     MD Coconut Vinegar 350ml  Pantry Staples      Vinegar
1262                Vinegar 350ml  Pantry Staples      Vinegar
1263          White vinegar 500ml  Pantry Staples      Vinegar
1264    MD Fresh Chilli & Vinegar  Pantry Staples      Vinegar
1265           Spring Water 600ml       Beverages        Water

[1266 rows x 3 columns]

In [59]:
#
sales_df = pd.merge(sales_df, item_categories_df, how = "left", on = ["item_name"])
sales_df.head(10)

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin,main_category,sub_category
0,4c4c9a80-b861-445e-9abc-6e70e84fd0d3,2/17/2017 12:17:17 AM,2003,Apples Pink Lady,0.140,cash,0.0,2.99,2.99,Fresh Produce,Apples
1,65d59c3b-b474-482f-8779-3249d6fee305,2/2/2017 10:14:16 PM,2003,Apples Pink Lady,0.146,cash,0.0,2.99,2.99,Fresh Produce,Apples
2,4443f4db-a5ba-4693-a6e1-70840ce6076e,2/21/2017 2:11:10 AM,2003,Apples Pink Lady,0.150,cash,0.0,2.99,2.99,Fresh Produce,Apples
3,3399ecfd-f809-4653-9310-d41015e09f8a,1/10/2017 3:11:14 AM,2003,Apples Pink Lady,0.152,cash,0.0,2.99,2.99,Fresh Produce,Apples
4,085663fa-1fde-4ffc-adfc-527599065a87,2/3/2017 2:16:10 AM,2003,Apples Pink Lady,0.162,cash,0.0,2.99,2.99,Fresh Produce,Apples
5,648880e7-8cc0-4f89-aee0-1110b5ee1570,2/8/2017 9:10:49 PM,2003,Apples Pink Lady,0.166,cash,0.0,2.99,2.99,Fresh Produce,Apples
6,e7aa2e2a-d259-4418-a05b-383db43c71fc,2/17/2017 8:17:02 PM,2003,Apples Pink Lady,0.168,cash,0.0,2.99,2.99,Fresh Produce,Apples
7,511f365b-987f-41a9-bde7-0461cb001b99,1/30/2017 9:20:47 PM,2003,Apples Pink Lady,0.178,cash,0.0,2.99,2.99,Fresh Produce,Apples
8,40192fc8-7edb-44db-bad7-ad913cc94657,2/21/2017 5:50:04 AM,2003,Apples Pink Lady,0.178,cash,0.0,2.99,2.99,Fresh Produce,Apples
9,6bb1cbb7-b49b-4324-9c13-f3534cdf5033,3/2/2017 3:41:23 AM,2003,Apples Pink Lady,0.180,cash,0.0,2.99,2.99,Fresh Produce,Apples

In [60]:
# Making my columns into title case
sales_df["item_name"] = sales_df["item_name"].str.title()
sales_df["payment_type"] = sales_df["payment_type"].str.title()
sales_df["main_category"] = sales_df["main_category"].str.title()
sales_df["sub_category"] = sales_df["sub_category"].str.title()
sales_df.sort_values("receipt_id").head(10)

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin,main_category,sub_category
14443,0001c063-2d32-4380-9db6-de20c5b48f59,1/16/2017 1:54:07 AM,2010,Banana Cavendish,1.364,Cash,2.0,1.99,-0.01,Fresh Produce,Bananas
95656,0001c063-2d32-4380-9db6-de20c5b48f59,1/16/2017 1:54:07 AM,1163,Brushed Potatoes 5Kg Bag,1.000,Cash,4.5,4.99,0.49,Fresh Produce,Potatoes
1171,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,2002,Apples Granny Smith,0.352,Cash,0.0,3.00,3.00,Fresh Produce,Apples
88419,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,2124,Mango 2For 3.00,1.000,Cash,0.0,3.00,3.00,Fresh Produce,Deals
94804,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,1073,Potato Desiree,1.370,Cash,0.0,2.99,2.99,Fresh Produce,Potatoes
91984,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,1008,Broccoli,0.626,Cash,0.0,3.50,3.50,Fresh Produce,Other Vegies
132330,0002a81e-5e13-4e0f-95fd-2f4a46c997fb,1/25/2017 10:24:42 PM,9322670000014,Carrots 1Kg,1.000,Cash,0.8,1.49,0.69,Fresh Produce,Carrots
219496,0002d6fc-1efa-43de-ba27-a683a1ee7ab8,5/20/2018 5:28:28 PM,9332769000139,Eggs 700G,1.000,Cash,2.7,3.20,0.50,"Dairy, Cheese, And Eggs",Eggs
206422,0002d6fc-1efa-43de-ba27-a683a1ee7ab8,5/20/2018 5:28:28 PM,2010,Banana Cavendish,1.436,Cash,2.0,1.99,-0.01,Fresh Produce,Bananas
215330,0002d6fc-1efa-43de-ba27-a683a1ee7ab8,5/20/2018 5:28:28 PM,2032,Orange Navel,1.426,Cash,0.0,2.99,2.99,Fresh Produce,Citrus Fruits

## Make the following columns (3 Points):
- Total Buying Price (Quantity * Unit Buying Price)
- Total Selling Price (Quantity * Unit Selling Price)
- Total Margin (Quantity * Unit Margin)

In [61]:
sales_df["total_buying_price"] = sales_df["quantity"] * sales_df["unit_buying_price"]
sales_df["total_selling_price"] = sales_df["quantity"] * sales_df["unit_selling_price"]
sales_df["total_margin"] = sales_df["quantity"] * sales_df["unit_price_margin"]
sales_df

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin,main_category,sub_category,total_buying_price,total_selling_price,total_margin
0,4c4c9a80-b861-445e-9abc-6e70e84fd0d3,2/17/2017 12:17:17 AM,2003,Apples Pink Lady,0.140,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.41860,0.41860
1,65d59c3b-b474-482f-8779-3249d6fee305,2/2/2017 10:14:16 PM,2003,Apples Pink Lady,0.146,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.43654,0.43654
2,4443f4db-a5ba-4693-a6e1-70840ce6076e,2/21/2017 2:11:10 AM,2003,Apples Pink Lady,0.150,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.44850,0.44850
3,3399ecfd-f809-4653-9310-d41015e09f8a,1/10/2017 3:11:14 AM,2003,Apples Pink Lady,0.152,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.45448,0.45448
4,085663fa-1fde-4ffc-adfc-527599065a87,2/3/2017 2:16:10 AM,2003,Apples Pink Lady,0.162,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.48438,0.48438
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372752,4abec176-1ca7-4b47-afc9-1679174161dd,10/1/2018 4:00:35 PM,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000
372753,863d4c09-d00c-4fdc-b8c6-0733244699c5,7/30/2018 4:20:44 PM,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000
372754,e9e84a1d-22ed-4302-8932-8ef52f9ac200,12/12/2018 1:27:30 PM,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000
372755,85c16d9f-5407-4922-a3d6-fa8bbed80688,8/17/2018 3:44:24 PM,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000
372756,b9d76d65-06d5-4e96-af68-c0f8f8d81566,10/9/2018 4:40:51 PM,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000

In [62]:
sales_df.loc[sales_df["quantity"] <=1,"quantity_type"] = "Single"
sales_df.loc[(sales_df["quantity"] >=1) & (sales_df["quantity"]<10), "quantity_type"] = "Regular"
sales_df.loc[sales_df["quantity"] >=10, "quantity_type"] = "Bulk"
sales_df.sample(10)

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin,main_category,sub_category,total_buying_price,total_selling_price,total_margin,quantity_type
310677,25440e1f-4500-44c9-b75c-82bce3c6255d,10/19/2018 12:17:03 PM,1099,Zucchini Green,0.590,Cash,0.00,3.50,3.50,Fresh Produce,Other Vegies,0.000,2.06500,2.06500,Single
263471,a8692969-9adb-442d-9e89-4d17c8614eb6,7/7/2018 5:07:18 PM,1111,Tomatoes Truss,0.088,Cash,0.00,5.99,5.99,Fresh Produce,Tomatoes,0.000,0.52712,0.52712,Single
264473,477ee1c2-31dd-4295-8f02-532b08572aa6,1/30/2018 1:24:55 PM,2048,Papaya Red,0.516,Cash,0.00,5.00,5.00,Fresh Produce,Tropical Fruits,0.000,2.58000,2.58000,Single
89593,bc23110a-560b-4552-a8f7-f32d59363b3e,2/25/2017 3:05:48 AM,1063,Onion Brown,1.324,Cash,0.00,1.99,1.99,Fresh Produce,Onions,0.000,2.63476,2.63476,Regular
43708,b62ee1b3-68f0-4b1c-9581-cbfa805fe45b,11/29/2017 10:01:09 AM,2045,Watermelon Seedless,1.900,Cash,1.00,1.49,0.49,Fresh Produce,Melons,1.900,2.83100,0.93100,Regular
1928,40243a9c-60fc-4683-95b6-ea35748b4741,2/19/2017 1:34:50 AM,2005,Apples Royal Gala,0.530,Cash,0.00,3.00,3.00,Fresh Produce,Apples,0.000,1.59000,1.59000,Single
42619,a551440a-d2ca-4b0a-a762-eac3fd43636f,1/16/2017 10:46:16 PM,2045,Watermelon Seedless,2.066,Cash,1.00,1.49,0.49,Fresh Produce,Melons,2.066,3.07834,1.01234,Regular
123662,aa969d3d-0100-4364-9d9c-9f3cb126562c,11/12/2017 10:54:02 AM,1076,Potato Sweet Gold,0.866,Cash,0.00,2.99,2.99,Fresh Produce,Potatoes,0.000,2.58934,2.58934,Single
121296,00032d46-cf9e-4b0b-b003-2f6bb5ab3e85,5/2/2017 1:33:13 PM,1071,Potato Brushed,1.140,Cash,2.25,2.50,0.25,Fresh Produce,Potatoes,2.565,2.85000,0.28500,Regular
156329,037bc567-1761-40f0-bee0-0e9e504dca9b,7/5/2017 10:46:02 AM,1058,Mushroom Cup,0.374,Magcard,5.00,8.99,3.99,Fresh Produce,Mushrooms,1.870,3.36226,1.49226,Single

In [63]:
# Sales DataTypes
sales_df.dtypes

receipt_id              object
date                    object
item_code                int64
item_name               object
quantity               float64
payment_type            object
unit_buying_price      float64
unit_selling_price     float64
unit_price_margin      float64
main_category           object
sub_category            object
total_buying_price     float64
total_selling_price    float64
total_margin           float64
quantity_type           object
dtype: object

In [64]:
sales_df["date"] = pd.to_datetime(sales_df["date"])
sales_df.dtypes

receipt_id                     object
date                   datetime64[ns]
item_code                       int64
item_name                      object
quantity                      float64
payment_type                   object
unit_buying_price             float64
unit_selling_price            float64
unit_price_margin             float64
main_category                  object
sub_category                   object
total_buying_price            float64
total_selling_price           float64
total_margin                  float64
quantity_type                  object
dtype: object

In [65]:
# Add these time columns in for yourselves
sales_df["year"] = sales_df["date"].dt.year
sales_df["quarter"] = sales_df["date"].dt.quarter
sales_df["month"] = sales_df["date"].dt.month_name()
sales_df["day"] = sales_df["date"].dt.day_name()
sales_df

,receipt_id,date,item_code,item_name,quantity,payment_type,unit_buying_price,unit_selling_price,unit_price_margin,main_category,sub_category,total_buying_price,total_selling_price,total_margin,quantity_type,year,quarter,month,day
0,4c4c9a80-b861-445e-9abc-6e70e84fd0d3,2017-02-17 00:17:17,2003,Apples Pink Lady,0.140,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.41860,0.41860,Single,2017,1,February,Friday
1,65d59c3b-b474-482f-8779-3249d6fee305,2017-02-02 22:14:16,2003,Apples Pink Lady,0.146,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.43654,0.43654,Single,2017,1,February,Thursday
2,4443f4db-a5ba-4693-a6e1-70840ce6076e,2017-02-21 02:11:10,2003,Apples Pink Lady,0.150,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.44850,0.44850,Single,2017,1,February,Tuesday
3,3399ecfd-f809-4653-9310-d41015e09f8a,2017-01-10 03:11:14,2003,Apples Pink Lady,0.152,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.45448,0.45448,Single,2017,1,January,Tuesday
4,085663fa-1fde-4ffc-adfc-527599065a87,2017-02-03 02:16:10,2003,Apples Pink Lady,0.162,Cash,0.0,2.99,2.99,Fresh Produce,Apples,0.0,0.48438,0.48438,Single,2017,1,February,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
372752,4abec176-1ca7-4b47-afc9-1679174161dd,2018-10-01 16:00:35,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000,Regular,2018,4,October,Monday
372753,863d4c09-d00c-4fdc-b8c6-0733244699c5,2018-07-30 16:20:44,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000,Regular,2018,3,July,Monday
372754,e9e84a1d-22ed-4302-8932-8ef52f9ac200,2018-12-12 13:27:30,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000,Regular,2018,4,December,Wednesday
372755,85c16d9f-5407-4922-a3d6-fa8bbed80688,2018-08-17 15:44:24,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000,Regular,2018,3,August,Friday
372756,b9d76d65-06d5-4e96-af68-c0f8f8d81566,2018-10-09 16:40:51,1232,Onion Brown 2Kg Large,1.000,Magcard,3.5,4.50,1.00,Pantry Staples,Condiments,3.5,4.50000,1.00000,Regular,2018,4,October,Tuesday

## Items Analysis

In [66]:
items_df = sales_df.groupby(["item_name", "main_category", "sub_category"]).agg(unit_buying_price = ("unit_buying_price", "mean"),
                                                                                unit_selling_price = ("unit_selling_price", "mean"),
                                                                                unit_price_margin = ("unit_price_margin", "mean"),
                                                                                quantity = ("quantity", "sum"),
                                                                                revenue = ("total_selling_price", "sum"),
                                                                                profit = ("total_margin", "sum"))
items_df

,,,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
item_name,main_category,sub_category,,,,,,
1Kg Olive Pack,Fresh Produce,Other Vegies,6.99,10.00,3.01,9.088,90.88000,27.35488
1Lt Coconut Oil,Pantry Staples,Oil,0.28,14.00,13.72,80.000,1120.00000,1097.60000
1Lt Coconut Oil Ver,Pantry Staples,Oil,0.00,14.00,14.00,10.000,140.00000,140.00000
2Kg Marsh Grapefruit,Fresh Produce,Citrus Fruits,3.00,5.00,2.00,141.000,705.00000,282.00000
2Kg Royal Gala Apple,Fresh Produce,Apples,0.00,4.50,4.50,60.000,270.00000,270.00000
...,...,...,...,...,...,...,...,...
Yellow Mustard Seeds 100G,Pantry Staples,Spices,0.00,2.99,2.99,3.000,8.97000,8.97000
Yellow Split Peas 500G,Pantry Staples,Grains And Pulses,1.40,1.99,0.59,60.000,119.40000,35.40000
Zafarelli,Fresh Produce,Bunch Vegies,1.00,1.50,0.50,12.000,18.00000,6.00000
Zucchini Green,Fresh Produce,Other Vegies,0.00,3.50,3.50,2406.733,8423.56550,8423.56550
Zucchini Lebanese,Fresh Produce,Other Vegies,0.00,3.49,3.49,1.708,5.96092,5.96092

## What are my top 50 items by revenue?

In [79]:
top_50_items_revenue = items_df.sort_values("revenue", ascending = False).head(50)
top_50_items_revenue

,item_name,main_category,sub_category,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
61,Banana Cavendish,Fresh Produce,Bananas,2.00,1.99,-0.01,24348.693,48453.89907,-243.48693
1100,Watermelon Seedless,Fresh Produce,Melons,1.00,1.49,0.49,20791.036,30978.64364,10187.60764
442,Field Tomatoes,Fresh Produce,Tomatoes,1.60,2.99,1.39,7428.811,22212.14489,10326.04729
424,Eggplant,Fresh Produce,Other Vegies,0.00,6.99,6.99,2797.440,19554.10560,19554.10560
178,Cherries,Fresh Produce,Other Fruits,0.00,15.99,15.99,1113.293,17801.55507,17801.55507
426,Eggs 700G,"Dairy, Cheese, And Eggs",Eggs,2.70,3.20,0.50,4926.000,15763.20000,2463.00000
591,Lettuce Iceberg,Fresh Produce,Lettuces,0.00,2.50,2.50,5812.000,14530.00000,14530.00000
33,Apples Pink Lady,Fresh Produce,Apples,0.00,2.99,2.99,4273.474,12777.68726,12777.68726
270,Cucumber Lebanese,Fresh Produce,Cucumbers,0.00,4.99,4.99,2476.144,12355.95856,12355.95856
155,Capsicum Red,Fresh Produce,Capsicum,0.00,4.99,4.99,2407.521,12013.52979,12013.52979
864,Potato Sweet Gold,Fresh Produce,Potatoes,0.00,2.99,2.99,3812.922,11400.63678,11400.63678
813,Pear Packham,Fresh Produce,Pears,2.00,2.99,0.99,3600.093,10764.27807,3564.09207
780,Papaya Red,Fresh Produce,Tropical Fruits,0.00,5.00,5.00,2128.820,10644.10000,10644.10000
765,Orange Navel,Fresh Produce,Citrus Fruits,0.00,2.99,2.99,3451.104,10318.80096,10318.80096
640,Mandarin Imperial,Fresh Produce,Citrus Fruits,1.00,2.50,1.50,4121.470,10303.67500,6182.20500
1059,Tomatoes Truss,Fresh Produce,Tomatoes,0.00,5.99,5.99,1717.310,10286.68690,10286.68690
858,Potato Brushed,Fresh Produce,Potatoes,2.25,2.50,0.25,4087.434,10218.58500,1021.85850
747,Okra,Fresh Produce,Asian Vegies,8.35,9.99,1.64,1004.205,10032.00795,1646.89620
875,Pumpkin Japanese/Kent,Fresh Produce,Pumpkins,0.00,1.99,1.99,4884.189,9719.53611,9719.53611
866,Potatoes Red 5Kg,Fresh Produce,Potatoes,0.00,6.00,6.00,1602.000,9612.00000,9612.00000
738,Nectarine White,Fresh Produce,Stonefruits,1.20,2.99,1.79,3209.975,9597.82525,5745.85525
503,Grapes Black,Fresh Produce,Grapes,0.00,3.99,3.99,2384.434,9513.89166,9513.89166
122,Broccoli,Fresh Produce,Other Vegies,0.00,3.50,3.50,2544.840,8906.94000,8906.94000
90,Berries Strawberry (Medium),Fresh Produce,Berries,0.00,2.50,2.50,3444.000,8610.00000,8610.00000
269,Cucumber Continental,Fresh Produce,Cucumbers,0.00,1.50,1.50,5720.000,8580.00000,8580.00000
265,Crimson Grapes,Fresh Produce,Grapes,0.00,4.99,4.99,1710.352,8534.65648,8534.65648
865,Potato Washed,Fresh Produce,Potatoes,0.00,2.99,2.99,2845.250,8507.29750,8507.29750
1058,Tomatoes Roma,Fresh Produce,Tomatoes,0.00,4.99,4.99,1703.746,8501.69254,8501.69254
1134,Zucchini Green,Fresh Produce,Other Vegies,0.00,3.50,3.50,2406.733,8423.56550,8423.56550
721,Mushroom Cup,Fresh Produce,Mushrooms,5.00,8.99,3.99,933.177,8389.26123,3723.37623
762,Onion Spring,Fresh Produce,Bunch Vegies,0.60,1.50,0.90,5586.000,8379.00000,5027.40000
859,Potato Desiree,Fresh Produce,Potatoes,0.00,2.99,2.99,2797.904,8365.73296,8365.73296
169,Cauliflower,Fresh Produce,Other Vegies,2.00,2.99,0.99,2787.136,8333.53664,2759.26464
249,Coriander,Fresh Produce,Herbs,0.00,1.99,1.99,4105.000,8168.95000,8168.95000
30,Apples Fuji,Fresh Produce,Apples,0.00,3.99,3.99,2030.770,8102.77230,8102.77230
755,Onion Brown 2Kg Large,Pantry Staples,Condiments,3.50,4.50,1.00,1731.000,7789.50000,1731.00000
582,Leek,Fresh Produce,Other Vegies,1.00,2.00,1.00,3815.000,7630.00000,3815.00000
172,Celery,Fresh Produce,Bunch Vegies,0.00,2.99,2.99,2496.000,7463.04000,7463.04000
35,Apples Royal Gala,Fresh Produce,Apples,0.00,3.00,3.00,2476.879,7430.63700,7430.63700
32,Apples Granny Smith,Fresh Produce,Apples,0.00,3.00,3.00,2447.338,7342.01400,7342.01400
81,Beans Green,Fresh Produce,Other Vegies,0.00,4.99,4.99,1422.583,7098.68917,7098.68917
1096,Wash Potatoes 5Kg,Fresh Produce,Potatoes,0.00,6.00,6.00,1148.000,6888.00000,6888.00000
986,Spinach Bunch,Fresh Produce,Bunch Vegies,0.00,3.00,3.00,2295.000,6885.00000,6885.00000
89,Berries Strawberry (Large),Fresh Produce,Berries,3.33,3.80,0.47,1675.000,6365.00000,787.25000
472,Garlic Chinese 500G,Fresh Produce,Onions,0.00,2.50,2.50,2512.000,6280.00000,6280.00000
804,Peaches White,Fresh Produce,Stonefruits,0.00,3.50,3.50,1771.921,6201.72350,6201.72350
507,Grapes White Seedless,Fresh Produce,Grapes,0.00,2.99,2.99,2041.871,6105.19429,6105.19429
832,Pineapple,Fresh Produce,Tropical Fruits,0.00,4.50,4.50,1322.000,5949.00000,5949.00000
474,Garlic Loose,Fresh Produce,Garlic,0.00,10.00,10.00,583.224,5832.24000,5832.24000
739,Nectarine Yellow,Fresh Produce,Stonefruits,0.00,2.99,2.99,1899.376,5679.13424,5679.13424

## What are my top 50 items by quantity?

In [80]:
top_50_items_quantity = items_df.sort_values("quantity", ascending = False).head(50)
top_50_items_quantity

,item_name,main_category,sub_category,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
61,Banana Cavendish,Fresh Produce,Bananas,2.00,1.99,-0.01,24348.693,48453.89907,-243.48693
1100,Watermelon Seedless,Fresh Produce,Melons,1.00,1.49,0.49,20791.036,30978.64364,10187.60764
442,Field Tomatoes,Fresh Produce,Tomatoes,1.60,2.99,1.39,7428.811,22212.14489,10326.04729
591,Lettuce Iceberg,Fresh Produce,Lettuces,0.00,2.50,2.50,5812.000,14530.00000,14530.00000
269,Cucumber Continental,Fresh Produce,Cucumbers,0.00,1.50,1.50,5720.000,8580.00000,8580.00000
762,Onion Spring,Fresh Produce,Bunch Vegies,0.60,1.50,0.90,5586.000,8379.00000,5027.40000
426,Eggs 700G,"Dairy, Cheese, And Eggs",Eggs,2.70,3.20,0.50,4926.000,15763.20000,2463.00000
875,Pumpkin Japanese/Kent,Fresh Produce,Pumpkins,0.00,1.99,1.99,4884.189,9719.53611,9719.53611
33,Apples Pink Lady,Fresh Produce,Apples,0.00,2.99,2.99,4273.474,12777.68726,12777.68726
640,Mandarin Imperial,Fresh Produce,Citrus Fruits,1.00,2.50,1.50,4121.470,10303.67500,6182.20500
249,Coriander,Fresh Produce,Herbs,0.00,1.99,1.99,4105.000,8168.95000,8168.95000
858,Potato Brushed,Fresh Produce,Potatoes,2.25,2.50,0.25,4087.434,10218.58500,1021.85850
582,Leek,Fresh Produce,Other Vegies,1.00,2.00,1.00,3815.000,7630.00000,3815.00000
864,Potato Sweet Gold,Fresh Produce,Potatoes,0.00,2.99,2.99,3812.922,11400.63678,11400.63678
163,Carrots 1Kg,Fresh Produce,Carrots,0.80,1.49,0.69,3638.000,5420.62000,2510.22000
813,Pear Packham,Fresh Produce,Pears,2.00,2.99,0.99,3600.093,10764.27807,3564.09207
765,Orange Navel,Fresh Produce,Citrus Fruits,0.00,2.99,2.99,3451.104,10318.80096,10318.80096
90,Berries Strawberry (Medium),Fresh Produce,Berries,0.00,2.50,2.50,3444.000,8610.00000,8610.00000
738,Nectarine White,Fresh Produce,Stonefruits,1.20,2.99,1.79,3209.975,9597.82525,5745.85525
865,Potato Washed,Fresh Produce,Potatoes,0.00,2.99,2.99,2845.250,8507.29750,8507.29750
859,Potato Desiree,Fresh Produce,Potatoes,0.00,2.99,2.99,2797.904,8365.73296,8365.73296
424,Eggplant,Fresh Produce,Other Vegies,0.00,6.99,6.99,2797.440,19554.10560,19554.10560
169,Cauliflower,Fresh Produce,Other Vegies,2.00,2.99,0.99,2787.136,8333.53664,2759.26464
873,Pumpkin Butternut,Fresh Produce,Pumpkins,0.00,1.99,1.99,2663.542,5300.44858,5300.44858
122,Broccoli,Fresh Produce,Other Vegies,0.00,3.50,3.50,2544.840,8906.94000,8906.94000
472,Garlic Chinese 500G,Fresh Produce,Onions,0.00,2.50,2.50,2512.000,6280.00000,6280.00000
172,Celery,Fresh Produce,Bunch Vegies,0.00,2.99,2.99,2496.000,7463.04000,7463.04000
35,Apples Royal Gala,Fresh Produce,Apples,0.00,3.00,3.00,2476.879,7430.63700,7430.63700
270,Cucumber Lebanese,Fresh Produce,Cucumbers,0.00,4.99,4.99,2476.144,12355.95856,12355.95856
32,Apples Granny Smith,Fresh Produce,Apples,0.00,3.00,3.00,2447.338,7342.01400,7342.01400
155,Capsicum Red,Fresh Produce,Capsicum,0.00,4.99,4.99,2407.521,12013.52979,12013.52979
1134,Zucchini Green,Fresh Produce,Other Vegies,0.00,3.50,3.50,2406.733,8423.56550,8423.56550
1015,Sweet Corn,Fresh Produce,Other Vegies,0.00,1.20,1.20,2404.000,2884.80000,2884.80000
503,Grapes Black,Fresh Produce,Grapes,0.00,3.99,3.99,2384.434,9513.89166,9513.89166
986,Spinach Bunch,Fresh Produce,Bunch Vegies,0.00,3.00,3.00,2295.000,6885.00000,6885.00000
753,Onion Brown,Fresh Produce,Onions,0.00,1.99,1.99,2267.319,4511.96481,4511.96481
52,Avocado Hass Large,Fresh Produce,Avocadoes,1.50,2.50,1.00,2249.000,5622.50000,2249.00000
780,Papaya Red,Fresh Produce,Tropical Fruits,0.00,5.00,5.00,2128.820,10644.10000,10644.10000
162,Carrots,Fresh Produce,Carrots,0.00,1.70,1.70,2124.978,3612.46260,3612.46260
507,Grapes White Seedless,Fresh Produce,Grapes,0.00,2.99,2.99,2041.871,6105.19429,6105.19429
30,Apples Fuji,Fresh Produce,Apples,0.00,3.99,3.99,2030.770,8102.77230,8102.77230
560,Kensington Pride Mango,Fresh Produce,Fruits,0.00,2.00,2.00,1907.234,3814.46800,3814.46800
739,Nectarine Yellow,Fresh Produce,Stonefruits,0.00,2.99,2.99,1899.376,5679.13424,5679.13424
584,Lemon,Fresh Produce,Citrus Fruits,0.00,2.99,2.99,1879.221,5618.87079,5618.87079
804,Peaches White,Fresh Produce,Stonefruits,0.00,3.50,3.50,1771.921,6201.72350,6201.72350
771,Pac Choy 3 For $2.,Fresh Produce,Deals,1.80,2.00,0.20,1746.000,3492.00000,349.20000
811,Pear Corella,Fresh Produce,Pears,2.50,3.00,0.50,1744.257,5232.77100,872.12850
755,Onion Brown 2Kg Large,Pantry Staples,Condiments,3.50,4.50,1.00,1731.000,7789.50000,1731.00000
1059,Tomatoes Truss,Fresh Produce,Tomatoes,0.00,5.99,5.99,1717.310,10286.68690,10286.68690
265,Crimson Grapes,Fresh Produce,Grapes,0.00,4.99,4.99,1710.352,8534.65648,8534.65648

## What are my top 50 items by profit?

In [69]:
top_50_items_profit = items_df.sort_values("profit", ascending = False).head(50)
top_50_items_profit

,,,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
item_name,main_category,sub_category,,,,,,
Eggplant,Fresh Produce,Other Vegies,0.0,6.99,6.99,2797.440,19554.10560,19554.10560
Cherries,Fresh Produce,Other Fruits,0.0,15.99,15.99,1113.293,17801.55507,17801.55507
Lettuce Iceberg,Fresh Produce,Lettuces,0.0,2.50,2.50,5812.000,14530.00000,14530.00000
Apples Pink Lady,Fresh Produce,Apples,0.0,2.99,2.99,4273.474,12777.68726,12777.68726
Cucumber Lebanese,Fresh Produce,Cucumbers,0.0,4.99,4.99,2476.144,12355.95856,12355.95856
Capsicum Red,Fresh Produce,Capsicum,0.0,4.99,4.99,2407.521,12013.52979,12013.52979
Potato Sweet Gold,Fresh Produce,Potatoes,0.0,2.99,2.99,3812.922,11400.63678,11400.63678
Papaya Red,Fresh Produce,Tropical Fruits,0.0,5.00,5.00,2128.820,10644.10000,10644.10000
Field Tomatoes,Fresh Produce,Tomatoes,1.6,2.99,1.39,7428.811,22212.14489,10326.04729
Orange Navel,Fresh Produce,Citrus Fruits,0.0,2.99,2.99,3451.104,10318.80096,10318.80096
Tomatoes Truss,Fresh Produce,Tomatoes,0.0,5.99,5.99,1717.310,10286.68690,10286.68690
Watermelon Seedless,Fresh Produce,Melons,1.0,1.49,0.49,20791.036,30978.64364,10187.60764
Pumpkin Japanese/Kent,Fresh Produce,Pumpkins,0.0,1.99,1.99,4884.189,9719.53611,9719.53611
Potatoes Red 5Kg,Fresh Produce,Potatoes,0.0,6.00,6.00,1602.000,9612.00000,9612.00000
Grapes Black,Fresh Produce,Grapes,0.0,3.99,3.99,2384.434,9513.89166,9513.89166
Broccoli,Fresh Produce,Other Vegies,0.0,3.50,3.50,2544.840,8906.94000,8906.94000
Berries Strawberry (Medium),Fresh Produce,Berries,0.0,2.50,2.50,3444.000,8610.00000,8610.00000
Cucumber Continental,Fresh Produce,Cucumbers,0.0,1.50,1.50,5720.000,8580.00000,8580.00000
Crimson Grapes,Fresh Produce,Grapes,0.0,4.99,4.99,1710.352,8534.65648,8534.65648
Potato Washed,Fresh Produce,Potatoes,0.0,2.99,2.99,2845.250,8507.29750,8507.29750
Tomatoes Roma,Fresh Produce,Tomatoes,0.0,4.99,4.99,1703.746,8501.69254,8501.69254
Zucchini Green,Fresh Produce,Other Vegies,0.0,3.50,3.50,2406.733,8423.56550,8423.56550
Potato Desiree,Fresh Produce,Potatoes,0.0,2.99,2.99,2797.904,8365.73296,8365.73296
Coriander,Fresh Produce,Herbs,0.0,1.99,1.99,4105.000,8168.95000,8168.95000
Apples Fuji,Fresh Produce,Apples,0.0,3.99,3.99,2030.770,8102.77230,8102.77230
Celery,Fresh Produce,Bunch Vegies,0.0,2.99,2.99,2496.000,7463.04000,7463.04000
Apples Royal Gala,Fresh Produce,Apples,0.0,3.00,3.00,2476.879,7430.63700,7430.63700
Apples Granny Smith,Fresh Produce,Apples,0.0,3.00,3.00,2447.338,7342.01400,7342.01400
Beans Green,Fresh Produce,Other Vegies,0.0,4.99,4.99,1422.583,7098.68917,7098.68917
Wash Potatoes 5Kg,Fresh Produce,Potatoes,0.0,6.00,6.00,1148.000,6888.00000,6888.00000
Spinach Bunch,Fresh Produce,Bunch Vegies,0.0,3.00,3.00,2295.000,6885.00000,6885.00000
Garlic Chinese 500G,Fresh Produce,Onions,0.0,2.50,2.50,2512.000,6280.00000,6280.00000
Peaches White,Fresh Produce,Stonefruits,0.0,3.50,3.50,1771.921,6201.72350,6201.72350
Mandarin Imperial,Fresh Produce,Citrus Fruits,1.0,2.50,1.50,4121.470,10303.67500,6182.20500
Grapes White Seedless,Fresh Produce,Grapes,0.0,2.99,2.99,2041.871,6105.19429,6105.19429
Pineapple,Fresh Produce,Tropical Fruits,0.0,4.50,4.50,1322.000,5949.00000,5949.00000
Garlic Loose,Fresh Produce,Garlic,0.0,10.00,10.00,583.224,5832.24000,5832.24000
Nectarine White,Fresh Produce,Stonefruits,1.2,2.99,1.79,3209.975,9597.82525,5745.85525
Nectarine Yellow,Fresh Produce,Stonefruits,0.0,2.99,2.99,1899.376,5679.13424,5679.13424
Lemon,Fresh Produce,Citrus Fruits,0.0,2.99,2.99,1879.221,5618.87079,5618.87079
Flower Pot,Flowers,Flowers,0.0,10.00,10.00,552.000,5520.00000,5520.00000
Peaches Yellow,Fresh Produce,Stonefruits,0.0,3.99,3.99,1373.376,5479.77024,5479.77024
Pumpkin Butternut,Fresh Produce,Pumpkins,0.0,1.99,1.99,2663.542,5300.44858,5300.44858
Capsicum Green,Fresh Produce,Capsicum,0.0,4.99,4.99,1043.000,5204.57000,5204.57000
Onion Spring,Fresh Produce,Bunch Vegies,0.6,1.50,0.90,5586.000,8379.00000,5027.40000
Peach Clingstone,Fresh Produce,Stonefruits,0.0,3.99,3.99,1188.271,4741.20129,4741.20129
Kiwi Fruit Green,Fresh Produce,Other Fruits,0.0,5.50,5.50,860.914,4735.02700,4735.02700
Salted Olives Black,Fresh Produce,Other Vegies,0.0,9.99,9.99,459.980,4595.20020,4595.20020
Ginger,Fresh Produce,Other Vegies,0.0,10.00,10.00,458.882,4588.82000,4588.82000
Onion Brown,Fresh Produce,Onions,0.0,1.99,1.99,2267.319,4511.96481,4511.96481

In [70]:
# Resetting the index of itmes df
items_df = items_df.reset_index()
items_df

,item_name,main_category,sub_category,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
0,1Kg Olive Pack,Fresh Produce,Other Vegies,6.99,10.00,3.01,9.088,90.88000,27.35488
1,1Lt Coconut Oil,Pantry Staples,Oil,0.28,14.00,13.72,80.000,1120.00000,1097.60000
2,1Lt Coconut Oil Ver,Pantry Staples,Oil,0.00,14.00,14.00,10.000,140.00000,140.00000
3,2Kg Marsh Grapefruit,Fresh Produce,Citrus Fruits,3.00,5.00,2.00,141.000,705.00000,282.00000
4,2Kg Royal Gala Apple,Fresh Produce,Apples,0.00,4.50,4.50,60.000,270.00000,270.00000
...,...,...,...,...,...,...,...,...,...
1131,Yellow Mustard Seeds 100G,Pantry Staples,Spices,0.00,2.99,2.99,3.000,8.97000,8.97000
1132,Yellow Split Peas 500G,Pantry Staples,Grains And Pulses,1.40,1.99,0.59,60.000,119.40000,35.40000
1133,Zafarelli,Fresh Produce,Bunch Vegies,1.00,1.50,0.50,12.000,18.00000,6.00000
1134,Zucchini Green,Fresh Produce,Other Vegies,0.00,3.50,3.50,2406.733,8423.56550,8423.56550
1135,Zucchini Lebanese,Fresh Produce,Other Vegies,0.00,3.49,3.49,1.708,5.96092,5.96092

In [71]:
# Making our pantry items dataframe.
pantry_items_df = items_df.loc[items_df["main_category"]=="Pantry Staples"]
pantry_items_df.head(5)

,item_name,main_category,sub_category,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
1,1Lt Coconut Oil,Pantry Staples,Oil,0.28,14.00,13.72,80.0,1120.00,1097.60
2,1Lt Coconut Oil Ver,Pantry Staples,Oil,0.00,14.00,14.00,10.0,140.00,140.00
8,Adzuki Beans 500G,Pantry Staples,Grains And Pulses,2.00,2.69,0.69,68.0,182.92,46.92
10,Al Nakhil Tahina 454G,Pantry Staples,Grains And Pulses,4.00,4.99,0.99,45.0,224.55,44.55
16,Amami Papadam,Pantry Staples,Grains And Pulses,1.15,1.99,0.84,34.0,67.66,28.56

In [72]:
# Calculate the revenue, investment, profit for the pantry staples section.

total_revenue = pantry_items_df.revenue.sum()
total_profit = pantry_items_df.profit.sum()
total_investment = total_revenue - total_profit
is_profitable = total_revenue>total_investment

print("Pantry Staples Analysis:")
print("Investment:", total_investment)
print("Revenue:", total_revenue)
print("Profit:", total_profit)
print("Is Profitable:", is_profitable)

Pantry Staples Analysis:
Investment: 73654.79999999997
Revenue: 110112.26909079394
Profit: 36457.469090793966
Is Profitable: True

## Which items in Pantry Staples should we stop selling?
### If an item has sold less than 50 units in the last 2  years, potentially we may want to consider not selling it.

In [81]:
items_not_to_keep_df = pantry_items_df.loc[pantry_items_df["quantity"]<50]
items_not_to_keep_df.sort_values("quantity")

                revenue  quantity     profit
sub_category
Grapes        83.940000       6.0  12.000000
Masala        17.910000       9.0   8.910000
Sweet         57.909091      26.0  11.889091

## Which items in Pantry Staples are very popular by quantity?

In [74]:
most_popular_by_quantity_df = pantry_items_df.sort_values("quantity", ascending = False)
most_popular_by_quantity_df

,item_name,main_category,sub_category,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
755,Onion Brown 2Kg Large,Pantry Staples,Condiments,3.50,4.50,1.00,1731.0,7789.50,1731.00
399,Diced Tomatoes,Pantry Staples,Pasta,0.68,0.99,0.31,973.0,963.27,301.63
790,Passata 700G,Pantry Staples,Pasta,1.00,1.49,0.49,638.0,950.62,312.62
754,Onion Brown 10Kg,Pantry Staples,Condiments,2.50,7.99,5.49,624.0,4985.76,3425.76
820,Peeled Plum Tomatoes,Pantry Staples,Pasta,0.68,0.99,0.31,519.0,513.81,160.89
...,...,...,...,...,...,...,...,...,...
273,Cumin Powder 100G,Pantry Staples,Spices,0.00,2.99,2.99,1.0,2.99,2.99
128,Bruschetta Ai Peperoni,Pantry Staples,Condiments,4.00,4.99,0.99,1.0,4.99,0.99
303,Derana Bbq Sauce 350Ml,Pantry Staples,Sauces,2.40,3.99,1.59,1.0,3.99,1.59
958,Semolina 1Kg Fine Pattu,Pantry Staples,Flour,1.40,3.00,1.60,1.0,3.00,1.60
160,Cardamon Pods 100G,Pantry Staples,Grains And Pulses,3.80,4.99,1.19,1.0,4.99,1.19

## Which items in Pantry Staples are making us lose money (negative profit)?

In [75]:
loss_making_df = pantry_items_df.loc[pantry_items_df["profit"]<0]
loss_making_df

,item_name,main_category,sub_category,unit_buying_price,unit_selling_price,unit_price_margin,quantity,revenue,profit
126,Brown Onion 1Kg,Pantry Staples,Condiments,1.50,1.20,-0.30,132.0,158.40,-39.60
1085,Vinegar 350Ml,Pantry Staples,Vinegar,2.85,1.99,-0.86,9.0,17.91,-7.74

## Which items in Pantry Staples are making us the most profit?

In [78]:
profit_making_df = pantry_items_df.loc[pantry_items_df["profit"]>0].sort_values("profit", ascending = False)
profit_making_df

                        revenue  quantity       profit
sub_category
Condiments         18097.662727    3810.0  7221.802727
Spices             13747.160909    3447.0  5010.870909
Rice               19235.081818    1666.0  4769.861818
Grains And Pulses  10801.950000    3284.0  4692.830000
Oil                10275.420000    1063.0  3104.890000
Pasta               6540.810000    4008.0  2393.270000
Cocunut Products    5475.240000     442.0  1355.040000
Flour               3694.040000     945.0  1205.140000
Sauces              3580.559091     668.0  1084.889091
Pulses And Grains   2567.230000    1033.0   907.780000
Canned Food         1707.420000     858.0   849.420000
Sauce               2526.490000     427.0   681.320000
Coconut Products    2437.200000     602.0   660.400000
Sugar               1642.865454     431.0   505.415454
Canned Fish         1603.620000     389.0   396.270000
Sardines            1561.660000     240.0   385.510000
Dried Fish          1285.420000     183.0   349.270000
Pickle               977.130000     221.0   264.990000
Baking               779.800000      70.0   170.400000
Dry                  374.270000     145.0   133.220000
Condiment            332.760000      54.0   104.460000
Spides               319.360000      64.0    76.160000
Vinegar              241.860000      91.0    60.160000
Papad                147.500000      59.0    41.300000
Grapes                83.940000       6.0    12.000000
Sweet                 57.909091      26.0    11.889091
Masala                17.910000       9.0     8.910000

## Sub category analysis of the Pantry Staples Category

In [77]:
sub_category_df = pantry_items_df = pantry_items_df.groupby(["sub_category"]).agg(revenue = ("revenue", "sum"),
                                                                                  quantity = ("quantity", "sum"),
                                                                                  profit = ("profit", "sum"))
sub_category_df.sort_values("quantity",ascending=False)

                        revenue  quantity       profit
sub_category
Pasta               6540.810000    4008.0  2393.270000
Condiments         18097.662727    3810.0  7221.802727
Spices             13747.160909    3447.0  5010.870909
Grains And Pulses  10801.950000    3284.0  4692.830000
Rice               19235.081818    1666.0  4769.861818
Oil                10275.420000    1063.0  3104.890000
Pulses And Grains   2567.230000    1033.0   907.780000
Flour               3694.040000     945.0  1205.140000
Canned Food         1707.420000     858.0   849.420000
Sauces              3580.559091     668.0  1084.889091
Coconut Products    2437.200000     602.0   660.400000
Cocunut Products    5475.240000     442.0  1355.040000
Sugar               1642.865454     431.0   505.415454
Sauce               2526.490000     427.0   681.320000
Canned Fish         1603.620000     389.0   396.270000
Sardines            1561.660000     240.0   385.510000
Pickle               977.130000     221.0   264.990000
Dried Fish          1285.420000     183.0   349.270000
Dry                  374.270000     145.0   133.220000
Vinegar              241.860000      91.0    60.160000
Baking               779.800000      70.0   170.400000
Spides               319.360000      64.0    76.160000
Papad                147.500000      59.0    41.300000
Condiment            332.760000      54.0   104.460000
Sweet                 57.909091      26.0    11.889091
Masala                17.910000       9.0     8.910000
Grapes                83.940000       6.0    12.000000

In [83]:
items_not_to_keep_df.to_csv("Pantry Items Not to Keep.csv")
most_popular_by_quantity_df.to_csv("Most popular Pantry Items by Quantity.csv")
loss_making_df.to_csv("Loss Making Pantry Items.csv")
profit_making_df.to_csv("Profit Making Pantry Items.csv")
sub_category_df.to_csv("Pantry Sub Categories Analysis.csv")